"""Working out what a capture means.

The stages in this package read a capture and say something about it: which requests
carry the workflow, which values are inputs, and how one request depends on another.
They are deterministic, and every verdict names the rule behind it, so the reasoning can
be inspected rather than trusted.
"""

from __future__ import annotations

from trace2api.analyze.classify import (
    ClassifiedRequest,
    ClassifiedValue,
    ValueClassification,
    ValueRole,
    ValueRule,
    classify_values,
    render_classification,
)
from trace2api.analyze.diff import (
    REDACTED_DISPLAY,
    AlignedCaptures,
    AlignedRequest,
    AlignmentRule,
    CaptureDiff,
    ChangeKind,
    ComparedCapture,
    ComparedValue,
    PairedRequest,
    UnpairedRequest,
    ValueChange,
    align_captures,
    compare_requests,
    diff_captures,
    render_diff,
)
from trace2api.analyze.flow import (
    CaptureFlows,
    FlowEndpoint,
    FlowRule,
    TracedRequest,
    ValueFlow,
    render_flows,
    trace_flows,
)
from trace2api.analyze.graph import (
    Dependency,
    DependencyLink,
    GraphNode,
    RequestGraph,
    build_graph,
    graph_capture,
    render_graph,
)
from trace2api.analyze.graphql import (
    CaptureOperations,
    GraphQLOperation,
    GraphQLRule,
    OperationType,
    find_graphql_operations,
    render_graphql,
)
from trace2api.analyze.naming import (
    NamingProvider,
    NamingSuggestion,
    render_suggestions,
    suggest_unknowns,
)
from trace2api.analyze.pagination import (
    PaginatedRequest,
    PaginatedValue,
    PaginationDetection,
    PaginationRule,
    PaginationStyle,
    detect_pagination,
    render_pagination,
)
from trace2api.analyze.relevance import (
    DEFAULT_KEPT,
    Classification,
    FilterReport,
    FilterResult,
    FilterRule,
    Relevance,
    classify_capture,
    classify_entry,
    filter_capture,
)
from trace2api.analyze.summary import (
    UNDECLARED_CONTENT_TYPE,
    CaptureSummary,
    ContentTypeCount,
    render_summary,
    summarize_capture,
)
from trace2api.analyze.verify import (
    CaptureVerification,
    Mismatch,
    MismatchKind,
    ResponseComparison,
    VerificationOutcome,
    VerifiedRequest,
    compare_responses,
    render_verification,
    verify_capture,
)

__all__ = [
    "DEFAULT_KEPT",
    "REDACTED_DISPLAY",
    "UNDECLARED_CONTENT_TYPE",
    "AlignedCaptures",
    "AlignedRequest",
    "AlignmentRule",
    "CaptureDiff",
    "CaptureFlows",
    "CaptureOperations",
    "CaptureSummary",
    "CaptureVerification",
    "ChangeKind",
    "Classification",
    "ClassifiedRequest",
    "ClassifiedValue",
    "ComparedCapture",
    "ComparedValue",
    "ContentTypeCount",
    "Dependency",
    "DependencyLink",
    "FilterReport",
    "FilterResult",
    "FilterRule",
    "FlowEndpoint",
    "FlowRule",
    "GraphNode",
    "GraphQLOperation",
    "GraphQLRule",
    "Mismatch",
    "MismatchKind",
    "NamingProvider",
    "NamingSuggestion",
    "OperationType",
    "PaginatedRequest",
    "PaginatedValue",
    "PaginationDetection",
    "PaginationRule",
    "PaginationStyle",
    "PairedRequest",
    "Relevance",
    "RequestGraph",
    "ResponseComparison",
    "TracedRequest",
    "UnpairedRequest",
    "ValueChange",
    "ValueClassification",
    "ValueFlow",
    "ValueRole",
    "ValueRule",
    "VerificationOutcome",
    "VerifiedRequest",
    "align_captures",
    "build_graph",
    "classify_capture",
    "classify_entry",
    "classify_values",
    "compare_requests",
    "compare_responses",
    "detect_pagination",
    "diff_captures",
    "filter_capture",
    "find_graphql_operations",
    "graph_capture",
    "render_classification",
    "render_diff",
    "render_flows",
    "render_graph",
    "render_graphql",
    "render_pagination",
    "render_suggestions",
    "render_summary",
    "render_verification",
    "suggest_unknowns",
    "summarize_capture",
    "trace_flows",
    "verify_capture",
]
